# Generated by Django 6.0.2 on 2026-02-10 14:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2026, 2, 10, 14, 27, 43, 1720, tzinfo=datetime.timezone.utc))),
                ('created_at', models.DateTimeField(default=datetime.datetime(2026, 2, 10, 14, 24, 43, 1720, tzinfo=datetime.timezone.utc))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
