# Generated by Django 6.0.2 on 2026-02-17 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 17, 8, 39, 41, 702713, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 17, 8, 42, 41, 702713, tzinfo=datetime.timezone.utc)),
        ),
    ]
