# Generated by Django 6.0.2 on 2026-02-17 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_otp_created_at_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 17, 8, 50, 51, 241114, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 17, 8, 53, 51, 241114, tzinfo=datetime.timezone.utc)),
        ),
    ]
